# Generated by Django 3.0 on 2019-12-16 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDim',
            fields=[
                ('Cust_Acct', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Segment_Name', models.CharField(max_length=50)),
                ('SVC_Plan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('Calendar_Dt', models.DateField(primary_key=True, serialize=False)),
                ('Month_Nbr', models.IntegerField()),
                ('Month_Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LineDim',
            fields=[
                ('MTN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Device_Grouping', models.CharField(max_length=50)),
                ('Sales_Channel', models.CharField(max_length=50)),
                ('SVC_ACT_DT', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LimitFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LIMIT_DT', models.DateField()),
                ('LIMIT_TYPE', models.CharField(max_length=50)),
                ('Cust_Acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsf_eventapp.AccountDim')),
                ('MTN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsf_eventapp.LineDim')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EVENT_DT', models.DateField()),
                ('MTN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsf_eventapp.LineDim')),
            ],
        ),
    ]
