# Generated by Django 3.0 on 2019-12-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsf_eventapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EVENT_DT', models.DateField()),
                ('MTN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsf_eventapp.LineDim')),
            ],
        ),
    ]
